services:
  backend:
    build:
      context: ./backend
    container_name: rag-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: ./frontend
    container_name: rag-frontend
    ports:
      - "3000:80"
    env_file:
      - .env